-- Alpha conversion.
--
-- In the scope-bounded (de Bruijn) calculus of `FinScope.lean` there are no
-- bound-variable *names*, so alpha conversion is not a reduction one ever has
-- to perform: alpha-convertible terms are literally equal.  To *say* that, one
-- needs the named syntax, so this module introduces it:
--
--   * `NTerm`, lambda terms with named variables;
--   * `NTerm.rename x y t`, the renaming of the free occurrences of `x` by `y`;
--   * `—→α`, one step of alpha conversion (rename the bound variable of an
--     abstraction to a name that does not occur in its body), and its
--     congruence closure `≡α`;
--   * `NTerm.toDB`, the translation of a named term into a scope-bounded de
--     Bruijn term, relative to a naming context.
--
-- The theorem `AlphaEq.toDB_eq` then says that alpha-convertible named terms
-- have the *same* de Bruijn translation: alpha conversion is exactly the
-- identity of the scope-bounded calculus.
module

public import Plfl.ReallyUntypedLambda.Iwilare2AiGenerated.Basic

@[expose] public section

namespace FinScope

open Term

/-! ## 1. Named lambda terms -/

/-- Lambda terms with named variables. -/
inductive NTerm where
  | var : Nat → NTerm
  | abs : Nat → NTerm → NTerm
  | app : NTerm → NTerm → NTerm
  deriving DecidableEq, Repr

namespace NTerm

/-- All the names occurring in a term, free, bound or binding. -/
def vars : NTerm → List Nat
  | .var x => [x]
  | .abs x t => x :: vars t
  | .app a b => vars a ++ vars b

/-- Rename every *free* occurrence of the name `x` by the name `y`. -/
def rename (x y : Nat) : NTerm → NTerm
  | .var z => if z = x then .var y else .var z
  | .abs z t => if z = x then .abs z t else .abs z (rename x y t)
  | .app a b => .app (rename x y a) (rename x y b)

end NTerm

/-! ## 2. Alpha conversion -/

set_option hygiene false in
set_option quotPrecheck false in
infix:60 " —→α " => Alpha

/-- One step of alpha conversion: rename the bound variable of an abstraction
    to a name that does not occur in its body (so that nothing is captured),
    anywhere inside a term. -/
inductive Alpha : NTerm → NTerm → Prop
  | rename (x y : Nat) (t : NTerm) (hy : y ∉ t.vars) :
      --------------------
      .abs x t —→α .abs y (t.rename x y)
  | abs {t t' : NTerm} (x : Nat) :
      t —→α t'
      --------------------
      → .abs x t —→α .abs x t'
  | appL {a a' : NTerm} (b : NTerm) :
      a —→α a'
      --------------------
      → .app a b —→α .app a' b
  | appR {b b' : NTerm} (a : NTerm) :
      b —→α b'
      --------------------
      → .app a b —→α .app a b'

/-- Alpha equivalence: the equivalence relation generated by alpha
    conversion. -/
abbrev AlphaEq : NTerm → NTerm → Prop := Relation.EqvGen Alpha

@[inherit_doc] infix:60 " ≡α " => AlphaEq

theorem AlphaEq.refl (t : NTerm) : t ≡α t := Relation.EqvGen.refl _
theorem AlphaEq.symm {s t : NTerm} (h : s ≡α t) : t ≡α s := Relation.EqvGen.symm _ _ h
theorem AlphaEq.trans {s t u : NTerm} (h₁ : s ≡α t) (h₂ : t ≡α u) : s ≡α u :=
  Relation.EqvGen.trans _ _ _ h₁ h₂
theorem Alpha.toAlphaEq {s t : NTerm} (h : s —→α t) : s ≡α t := Relation.EqvGen.rel _ _ h

/-! ## 3. Translation into the scope-bounded calculus

A *naming context* for `Term n` is a list of `n` names, given as a function
`Fin n → Nat`; the index of a name is the position of its first occurrence. -/

namespace NTerm

/-- The de Bruijn index of the name `x` in the naming context `ctx`: the
    position of its first occurrence, if it has one. -/
def lookup : (n : Nat) → (Fin n → Nat) → Nat → Option (Fin n)
  | 0, _, _ => none
  | n + 1, ctx, x =>
      if ctx 0 = x then some 0 else (lookup n (fun i => ctx i.succ) x).map Fin.succ

/-- The de Bruijn translation of a named term in a naming context; it fails
    exactly on the terms with a free name outside the context. -/
def toDB : {n : Nat} → (Fin n → Nat) → NTerm → Option (Term n)
  | n, ctx, .var x => (lookup n ctx x).map Term.var
  | _, ctx, .abs x t => (toDB (Fin.cons x ctx) t).map Term.abs
  | _, ctx, .app a b =>
      match toDB ctx a, toDB ctx b with
      | some a', some b' => some (a' ⬝ b')
      | _, _ => none

@[simp] theorem toDB_var {n : Nat} (ctx : Fin n → Nat) (x : Nat) :
    toDB ctx (.var x) = (lookup n ctx x).map Term.var := rfl
@[simp] theorem toDB_abs {n : Nat} (ctx : Fin n → Nat) (x : Nat) (t : NTerm) :
    toDB ctx (.abs x t) = (toDB (Fin.cons x ctx) t).map Term.abs := rfl
@[simp] theorem toDB_app {n : Nat} (ctx : Fin n → Nat) (a b : NTerm) :
    toDB ctx (.app a b) =
      (match toDB ctx a, toDB ctx b with
        | some a', some b' => some (a' ⬝ b')
        | _, _ => none) := rfl

/-- The lookup in an extended context. -/
theorem lookup_cons {n : Nat} (w : Nat) (ctx : Fin n → Nat) (z : Nat) :
    lookup (n + 1) (Fin.cons w ctx) z =
      if w = z then some 0 else (lookup n ctx z).map Fin.succ := by
  rw [lookup]
  simp

end NTerm

/-! ### Alpha conversion does not change the de Bruijn translation -/

/-- Two contexts that cannot be told apart by any name other than `y`
    translate a term avoiding `y` in the same way. -/
theorem NTerm.toDB_congr {y : Nat} : ∀ (t : NTerm) {n : Nat} (c₁ c₂ : Fin n → Nat),
    (∀ z, z ≠ y → NTerm.lookup n c₁ z = NTerm.lookup n c₂ z) → y ∉ t.vars →
    NTerm.toDB c₁ t = NTerm.toDB c₂ t := by
  intro t
  induction t with
  | var x =>
      intro n c₁ c₂ h hy
      have hxy : x ≠ y := fun hx => hy (by simp [NTerm.vars, hx])
      simp only [NTerm.toDB_var, h x hxy]
  | abs w u ih =>
      intro n c₁ c₂ h hy
      have hy' : y ∉ u.vars := fun hm => hy (by simp [NTerm.vars, hm])
      have hsub : ∀ z, z ≠ y →
          NTerm.lookup (n + 1) (Fin.cons w c₁) z = NTerm.lookup (n + 1) (Fin.cons w c₂) z := by
        intro z hz
        rw [NTerm.lookup_cons, NTerm.lookup_cons, h z hz]
      simp only [NTerm.toDB_abs, ih (Fin.cons w c₁) (Fin.cons w c₂) hsub hy']
  | app a b iha ihb =>
      intro n c₁ c₂ h hy
      have hya : y ∉ a.vars := fun hm => hy (by simp [NTerm.vars, hm])
      have hyb : y ∉ b.vars := fun hm => hy (by simp [NTerm.vars, hm])
      simp only [NTerm.toDB_app, iha c₁ c₂ h hya, ihb c₁ c₂ h hyb]

/-- The key lemma: if `c₁` answers for `y` exactly what `c₂` answers for `x`
    (and both agree on every other name), then translating a renamed term in
    `c₁` is translating the term in `c₂`. -/
theorem NTerm.toDB_rename_eq {x y : Nat} : ∀ (t : NTerm) {n : Nat} (c₁ c₂ : Fin n → Nat),
    (∀ z, z ≠ y → NTerm.lookup n c₁ (if z = x then y else z) = NTerm.lookup n c₂ z) →
    y ∉ t.vars → NTerm.toDB c₁ (t.rename x y) = NTerm.toDB c₂ t := by
  intro t
  induction t with
  | var z =>
      intro n c₁ c₂ h hy
      have hzy : z ≠ y := fun hz => hy (by simp [NTerm.vars, hz])
      have hh := h z hzy
      cases hzx : decide (z = x) with
      | true =>
          have hzx' : z = x := of_decide_eq_true hzx
          simp only [if_pos hzx'] at hh
          simp only [NTerm.rename, if_pos hzx', NTerm.toDB_var, hh]
      | false =>
          have hzx' : ¬ (z = x) := of_decide_eq_false hzx
          simp only [if_neg hzx'] at hh
          simp only [NTerm.rename, if_neg hzx', NTerm.toDB_var, hh]
  | abs w u ih =>
      intro n c₁ c₂ h hy
      have hwy : ¬ (w = y) := fun hw => hy (by simp [NTerm.vars, hw])
      have hy' : y ∉ u.vars := fun hm => hy (by simp [NTerm.vars, hm])
      cases hwx : decide (w = x) with
      | true =>
          have hwx' : w = x := of_decide_eq_true hwx
          have hcong : ∀ z, z ≠ y →
              NTerm.lookup (n + 1) (Fin.cons w c₁) z = NTerm.lookup (n + 1) (Fin.cons w c₂) z := by
            intro z hz
            rw [NTerm.lookup_cons, NTerm.lookup_cons]
            cases hwz : decide (w = z) with
            | true =>
                have hwz' : w = z := of_decide_eq_true hwz
                simp only [if_pos hwz']
            | false =>
                have hwz' : ¬ (w = z) := of_decide_eq_false hwz
                have hzx : ¬ (z = x) := fun hzx => hwz' (hwx'.trans hzx.symm)
                have hh := h z hz
                simp only [if_neg hzx] at hh
                simp only [if_neg hwz', hh]
          simp only [NTerm.rename, if_pos hwx', NTerm.toDB_abs,
            NTerm.toDB_congr u (Fin.cons w c₁) (Fin.cons w c₂) hcong hy']
      | false =>
          have hwx' : ¬ (w = x) := of_decide_eq_false hwx
          have hsub : ∀ z, z ≠ y →
              NTerm.lookup (n + 1) (Fin.cons w c₁) (if z = x then y else z) =
                NTerm.lookup (n + 1) (Fin.cons w c₂) z := by
            intro z hz
            have hh := h z hz
            cases hzx : decide (z = x) with
            | true =>
                have hzx' : z = x := of_decide_eq_true hzx
                have hwz : ¬ (w = z) := fun hwz => hwx' (hwz.trans hzx')
                simp only [if_pos hzx'] at hh ⊢
                rw [NTerm.lookup_cons, NTerm.lookup_cons, if_neg hwy, if_neg hwz, hh]
            | false =>
                have hzx' : ¬ (z = x) := of_decide_eq_false hzx
                simp only [if_neg hzx'] at hh ⊢
                rw [NTerm.lookup_cons, NTerm.lookup_cons]
                cases hwz : decide (w = z) with
                | true =>
                    have hwz' : w = z := of_decide_eq_true hwz
                    simp only [if_pos hwz']
                | false =>
                    have hwz' : ¬ (w = z) := of_decide_eq_false hwz
                    simp only [if_neg hwz', hh]
          simp only [NTerm.rename, if_neg hwx', NTerm.toDB_abs,
            ih (Fin.cons w c₁) (Fin.cons w c₂) hsub hy']
  | app a b iha ihb =>
      intro n c₁ c₂ h hy
      have hya : y ∉ a.vars := fun hm => hy (by simp [NTerm.vars, hm])
      have hyb : y ∉ b.vars := fun hm => hy (by simp [NTerm.vars, hm])
      simp only [NTerm.rename, NTerm.toDB_app, iha c₁ c₂ h hya, ihb c₁ c₂ h hyb]

/-- **Alpha conversion is invisible in the de Bruijn calculus**: one step of
    alpha conversion does not change the translation. -/
theorem Alpha.toDB_eq {s t : NTerm} (h : s —→α t) : ∀ {n : Nat} (ctx : Fin n → Nat),
    NTerm.toDB ctx s = NTerm.toDB ctx t := by
  induction h with
  | rename x y t hy =>
      intro n ctx
      have hsim : ∀ z, z ≠ y →
          NTerm.lookup (n + 1) (Fin.cons y ctx) (if z = x then y else z) =
            NTerm.lookup (n + 1) (Fin.cons x ctx) z := by
        intro z hz
        cases hzx : decide (z = x) with
        | true =>
            have hzx' : z = x := of_decide_eq_true hzx
            simp only [if_pos hzx']
            rw [NTerm.lookup_cons, NTerm.lookup_cons, if_pos rfl, if_pos hzx'.symm]
        | false =>
            have hzx' : ¬ (z = x) := of_decide_eq_false hzx
            simp only [if_neg hzx']
            rw [NTerm.lookup_cons, NTerm.lookup_cons, if_neg (fun hyz : y = z => hz hyz.symm),
              if_neg (fun hxz : x = z => hzx' hxz.symm)]
      simp only [NTerm.toDB_abs, NTerm.toDB_rename_eq t (Fin.cons y ctx) (Fin.cons x ctx) hsim hy]
  | abs x _ ih => intro n ctx; simp only [NTerm.toDB_abs, ih (Fin.cons x ctx)]
  | appL b _ ih => intro n ctx; simp only [NTerm.toDB_app, ih ctx]
  | appR a _ ih => intro n ctx; simp only [NTerm.toDB_app, ih ctx]

/-- Alpha-equivalent named terms have the *same* scope-bounded de Bruijn
    translation: in `Term n`, alpha conversion is the identity. -/
theorem AlphaEq.toDB_eq {s t : NTerm} (h : s ≡α t) : ∀ {n : Nat} (ctx : Fin n → Nat),
    NTerm.toDB ctx s = NTerm.toDB ctx t := by
  induction h with
  | rel s t hst => exact fun ctx => hst.toDB_eq ctx
  | refl s => exact fun _ => rfl
  | symm s t _ ih => exact fun ctx => (ih ctx).symm
  | trans s t u _ _ ih₁ ih₂ => exact fun ctx => (ih₁ ctx).trans (ih₂ ctx)

/-! ## 4. Examples -/

/-- `λx. x` and `λy. y` are alpha-convertible... -/
example : NTerm.abs 0 (.var 0) ≡α NTerm.abs 1 (.var 1) :=
  (Alpha.rename 0 1 (.var 0) (by simp [NTerm.vars])).toAlphaEq

/-- ... and both translate to the same de Bruijn term `ƛ v#0`. -/
example : NTerm.toDB (n := 0) Fin.elim0 (NTerm.abs 0 (.var 0)) = some (ƛ v# 0) := by
  rfl

example : NTerm.toDB (n := 0) Fin.elim0 (NTerm.abs 1 (.var 1)) = some (ƛ v# 0) := by
  rfl

end FinScope
